export const deals = [
  {
    id: 1,
    title: "Wireless Earbuds",
    price: 1299,
    oldPrice: 2999,
    img: "/images/earbuds.webp",
  },
  {
    id: 2,
    title: "Smart Watch",
    price: 1899,
    oldPrice: 3999,
    img: "/images/smartwatch.jpg",
  },
  {
    id: 3,
    title: "Running Shoes",
    price: 999,
    oldPrice: 2499,
    img: "/images/hero1.webp",
  },
  {
    id: 4,
    title: "Makeup Kit",
    price: 499,
    oldPrice: 1299,
    img: "/images/beauty.webp",
  },
  {
    id: 5,
    title: "Bluetooth Speaker",
    price: 799,
    oldPrice: 1599,
    img: "/images/bluetooth.webp",
  },
  {
    id: 6,
    title: "Women Handbag",
    price: 1199,
    oldPrice: 2599,
    img: "/images/WomenHandbag.webp",
  },
  {
    id: 7,
    title: "Gaming Keyboard",
    price: 1599,
    oldPrice: 3499,
    img: "/images/GamingKeyboard.webp",
  },
  {
    id: 8,
    title: "Casual T-Shirt",
    price: 399,
    oldPrice: 899,
    img: "/images/CasualT-Shirt.webp",
  },
  {
    id: 9,
    title: "Hair Dryer",
    price: 699,
    oldPrice: 1499,
    img: "/images/HairDryer.webp",
  },
  {
    id: 10,
    title: "Sunglasses",
    price: 299,
    oldPrice: 999,
    img: "/images/Sunglasses.webp",
  },
];
