export const featuredProducts = [
  {
    id: 1,
    title: "Premium Wireless Earbuds",
    price: 1499,
    oldPrice: 2999,
    rating: 4.5,
    img: "/images/earbuds.webp",
  },
  {
    id: 2,
    title: "5G Smartphone",
    price: 11999,
    oldPrice: 15999,
    rating: 4.4,
    img: "/images/mobiles.webp",
  },
  {
    id: 3,
    title: "Running Shoes",
    price: 1299,
    oldPrice: 2499,
    rating: 4.1,
    img: "/images/hero1.webp",
  },
  {
    id: 4,
    title: "Bluetooth Speaker",
    price: 899,
    oldPrice: 1499,
    rating: 4.3,
    img: "/images/bluetooth.webp",
  },
  {
    id: 5,
    title: "Analog Men's Watch",
    price: 799,
    oldPrice: 1599,
    rating: 4.0,
    img: "/images/smartwatch.jpg",
  },
  {
    id: 6,
    title: "Gaming Keyboard",
    price: 1899,
    oldPrice: 3499,
    rating: 4.5,
    img: "/images/GamingKeyboard.webp",
  },
  {
    id: 7,
    title: "Smart Fitness Band",
    price: 1499,
    oldPrice: 2999,
    rating: 4.2,
    img: "/images/SmartFitnessBand.webp",
  },
  {
    id: 8,
    title: "Premium Headphones",
    price: 999,
    oldPrice: 1999,
    rating: 4.1,
    img: "/images/Sunglasses.webp",
  },
];
