export const products = [
  {
    id: 1,
    title: "Wireless Earbuds",
    category: "Electronics",
    price: 1299,
    rating: 4.3,
    img: "/images/earbuds.webp",
  },
  {
    id: 2,
    title: "Sports Shoes",
    category: "Fashion",
    price: 1499,
    rating: 4.1,
    img: "/images/shoes.webp",
  },
  {
    id: 3,
    title: "Smart Watch",
    category: "Electronics",
    price: 1999,
    rating: 4.4,
    img: "/images/smartwatch.webp",
  },
  {
    id: 4,
    title: "Bluetooth Speaker",
    category: "Electronics",
    price: 899,
    rating: 4.2,
    img: "/images/bluetooth.webp",
  },
  {
    id: 5,
    title: "Men’s T-Shirt",
    category: "Fashion",
    price: 499,
    rating: 4.0,
    img: "/images/tshirt.webp",
  },
  {
    id: 6,
    title: "Sunglasses",
    category: "Fashion",
    price: 299,
    rating: 4.2,
    img: "/images/sunglasses.webp",
  },
  {
    id: 7,
    title: "Mixer Grinder",
    category: "Home",
    price: 2499,
    rating: 4.3,
    img: "/images/home.webp",
  },
  {
    id: 8,
    title: "Makeup Kit",
    category: "Beauty",
    price: 699,
    rating: 4.1,
    img: "/images/beauty.webp",
  },
];
